### PR TITLE
Use the identifier property to compare objects if it exists

### PR DESCRIPTION
**Pull request by 0xced**

### CODE REVIEW

**Comment by nfarina** [comment]
Ping me on IM - would like to consider applying these changes to a new project that will supersede SMModelObject.

**Comment by nfarina** [comment]
4 years later!

**Comment by 0xced** [comment]
I just discovered https://github.com/pulls and I’m closing old open pull requests. 😀

**Comment by nfarina** [comment]
Ah nice, just did the same :)

**Pull request closed without merging**
